name: Tutor App Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deplou:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Frontend
        working-directory: ./frontend
        run: |
          cat > .env << EOF
          API_ENDPOINT=${{secrets.API_URL}}
          API_ENDPOINT_OLD=${{secrets.API_URL}}
          STRAPI_CLOUD_ENDPOINT=${{secrets.STRAPI_ENDPOINT}}
          MEDIA_ENDPOINT=${{secrets.MEDIA_URL}}

      - name: Backend
        working-directory: ./backend
        run: |
          HOST=0.0.0.0
          PORT=1337
          APP_KEYS=${{secrets.BACKEND_API_KEYS}}
          API_TOKEN_SALT=${{secrets.BACKEND_TOKEN_SALT}}
          ADMIN_JWT_SECRET=${{secrets.BACKEND_ADMIN_JWT_SECRET}}
          TRANSFER_TOKEN_SALT=${{secrets.BACKEND_TRANSFER_TOKEN_SALT}}
          DATABASE_SSL=false
          DATABASE_FILENAME=.tmp/data.db
          JWT_SECRET=${{secrets.ADMIN_JWT_SECRET}}

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd project-10xdev
            git checkout main
            git pull
            docker compose pull
            docker compose up -d --force-recreate
